UPDATE "categories" SET "icon" = CASE "slug"
  WHEN 'restaurants-cafes' THEN 'restaurant'
  WHEN 'beauty-wellness' THEN 'spa'
  WHEN 'legal-financial' THEN 'balance'
  WHEN 'home-services' THEN 'home-repair'
  WHEN 'automotive' THEN 'car'
  WHEN 'retail' THEN 'storefront'
  WHEN 'education' THEN 'school'
  WHEN 'medical' THEN 'medical'
  WHEN 'media-events' THEN 'celebration'
  WHEN 'travel-transport' THEN 'flight'
  ELSE "icon"
END;

UPDATE "sub_categories" SET "icon" = CASE "slug"
  WHEN 'persian-restaurant' THEN 'restaurant'
  WHEN 'cafe' THEN 'cafe'
  WHEN 'bakery' THEN 'bakery'
  WHEN 'hair-salon' THEN 'hair-salon'
  WHEN 'aesthetic-clinic' THEN 'aesthetic-clinic'
  WHEN 'spa-massage' THEN 'spa'
  WHEN 'law-office' THEN 'gavel'
  WHEN 'accounting' THEN 'accounting'
  WHEN 'insurance' THEN 'insurance'
  WHEN 'plumbing' THEN 'plumbing'
  WHEN 'electrical' THEN 'electrical'
  WHEN 'cleaning' THEN 'cleaning'
  WHEN 'repair-shop' THEN 'car-repair'
  WHEN 'car-wash' THEN 'car-wash'
  WHEN 'car-dealer' THEN 'car-dealer'
  WHEN 'iranian-grocery' THEN 'grocery'
  WHEN 'clothing' THEN 'clothing'
  WHEN 'home-appliances' THEN 'home-appliances'
  WHEN 'language-school' THEN 'language'
  WHEN 'music-school' THEN 'music'
  WHEN 'driving-school' THEN 'driving-school'
  WHEN 'dental-clinic' THEN 'dentist'
  WHEN 'general-practitioner' THEN 'doctor'
  WHEN 'psychology' THEN 'psychology'
  WHEN 'photo-studio' THEN 'camera'
  WHEN 'videography' THEN 'video'
  WHEN 'event-planning' THEN 'celebration'
  WHEN 'travel-agency' THEN 'travel'
  WHEN 'transport' THEN 'transport'
  WHEN 'car-rental' THEN 'car-rental'
  ELSE "icon"
END;
