UPDATE "tags" AS tag
SET "nameDe" = translations."nameDe"
FROM (
  VALUES
    ('popular', 'Beliebt'),
    ('halal', 'Halal'),
    ('free-delivery', 'Kostenlose Lieferung'),
    ('express-service', 'Express-Service'),
    ('parking', 'Parkplätze'),
    ('online-booking', 'Online-Buchung'),
    ('open-24h', 'Rund um die Uhr geöffnet'),
    ('budget-friendly', 'Preisgünstig'),
    ('legacy-specialty-7', 'Frisches Brot'),
    ('legacy-specialty-9', 'Haarfärbung'),
    ('legacy-specialty-19', 'Lohn- und Gehaltsabrechnung'),
    ('legacy-specialty-6', 'Desserts'),
    ('legacy-specialty-12', 'Laserbehandlung'),
    ('legacy-specialty-41', 'Gitarrenunterricht'),
    ('legacy-specialty-26', 'Haushaltsreinigung'),
    ('legacy-specialty-16', 'Vertragsrecht'),
    ('legacy-specialty-2', 'Persische Eintopfgerichte'),
    ('legacy-specialty-50', 'Eventfotografie'),
    ('legacy-specialty-55', 'Europareisen'),
    ('legacy-specialty-52', 'Werbevideos'),
    ('legacy-specialty-44', 'Zahnimplantate'),
    ('legacy-specialty-30', 'Fahrzeuginnenreinigung'),
    ('legacy-specialty-34', 'Herrenmode'),
    ('legacy-specialty-38', 'Deutschkurse'),
    ('legacy-specialty-1', 'Kebabgerichte'),
    ('legacy-specialty-15', 'Aufenthaltsrecht'),
    ('legacy-specialty-14', 'Therapeutische Massage'),
    ('legacy-specialty-4', 'Spezialitätenkaffee'),
    ('legacy-specialty-59', 'Tagesmiete'),
    ('legacy-specialty-43', 'Praktischer Fahrunterricht'),
    ('legacy-specialty-20', 'Kfz-Versicherung'),
    ('legacy-specialty-58', 'Frachtversand'),
    ('legacy-specialty-40', 'Klavierunterricht'),
    ('legacy-specialty-25', 'Beleuchtungsinstallation'),
    ('legacy-specialty-27', 'Büroreinigung'),
    ('legacy-specialty-28', 'Kfz-Mechanik'),
    ('legacy-specialty-24', 'Elektroverkabelung'),
    ('legacy-specialty-11', 'Haarstyling'),
    ('legacy-specialty-31', 'Gebrauchtwagen'),
    ('legacy-specialty-37', 'Küchengeräte'),
    ('legacy-specialty-49', 'Porträtfotografie'),
    ('legacy-specialty-39', 'Englischkurse'),
    ('legacy-specialty-22', 'Leckreparatur'),
    ('legacy-specialty-32', 'Neuwagen'),
    ('legacy-specialty-57', 'Umzugsservice'),
    ('legacy-specialty-60', 'Monatsmiete'),
    ('legacy-specialty-46', 'Allgemeinmedizinische Untersuchung'),
    ('legacy-specialty-23', 'Installation'),
    ('legacy-specialty-13', 'Gesichtsbehandlung'),
    ('legacy-specialty-10', 'Keratinbehandlung'),
    ('legacy-specialty-29', 'Fahrzeugdiagnose'),
    ('legacy-specialty-35', 'Damenmode'),
    ('legacy-specialty-51', 'Hochzeitsvideo'),
    ('legacy-specialty-45', 'Kieferorthopädie'),
    ('legacy-specialty-48', 'Familienangelegenheiten'),
    ('legacy-specialty-53', 'Veranstaltungsorganisation'),
    ('legacy-specialty-18', 'Steuerberatung'),
    ('legacy-specialty-54', 'Konferenzen'),
    ('legacy-specialty-42', 'Theorieunterricht'),
    ('legacy-specialty-36', 'Elektrogeräte'),
    ('legacy-specialty-47', 'Einzelberatung'),
    ('legacy-specialty-56', 'Tickets'),
    ('legacy-specialty-8', 'Traditionelles Gebäck'),
    ('legacy-specialty-3', 'Dizi (persischer Eintopf)'),
    ('legacy-specialty-21', 'Krankenversicherung'),
    ('legacy-specialty-5', 'Frühstück'),
    ('handicrafts', 'Kunsthandwerk'),
    ('household-goods', 'Haushaltswaren')
) AS translations("slug", "nameDe")
WHERE tag."slug" = translations."slug"
  AND (tag."nameDe" IS NULL OR BTRIM(tag."nameDe") = '');
