import "server-only";
import { getTranslations } from "next-intl/server";

export async function getBusinessDirectoryLabels() {
  const t = await getTranslations("Businesses");
  return {
    eyebrow: t("eyebrow"),
    title: t("title"),
    resultCount: t("resultCountTemplate", { count: "{count}" }),
    resultCountOne: t("resultCount", { count: 1 }),
    resultCountEmpty: t("resultCount", { count: 0 }),
    showing: t("showing", { from: "{from}", to: "{to}" }),
    loading: t("loading"),
    error: t("error"),
    retry: t("retry"),
    sort: {
      label: t("sort.label"),
      latest: t("sort.latest"),
      oldest: t("sort.oldest"),
      popular: t("sort.popular"),
    },
    card: {
      favorite: t("card.favorite"),
      reviews: t("card.reviewsTemplate", { count: "{count}" }),
      unknownLocation: t("card.unknownLocation"),
      distance: t("card.distance", { distance: "{distance}" }),
      featured: t("card.featured"),
      openNow: t("card.openNow"),
      closed: t("card.closed"),
      openSoon: t("card.openSoon", { time: "{time}" }),
      closeSoon: t("card.closeSoon", { time: "{time}" }),
    },
    empty: { title: t("empty.title"), description: t("empty.description") },
    pagination: {
      label: t("pagination.label"),
      previous: t("pagination.previous"),
      next: t("pagination.next"),
    },
    map: {
      show: t("map.show"),
      hide: t("map.hide"),
      title: t("map.title"),
      loading: t("map.loading"),
      error: t("map.error"),
      truncated: t("map.truncated"),
      clusterResults: t("map.clusterResults", { count: "{count}" }),
      viewBusiness: t("map.viewBusiness"),
      reviews: t("map.reviews"),
      directions: t("map.directions"),
    },
    allFilters: t("filters.all"),
    closeFilters: t("filters.close"),
    filters: {
      title: t("filters.title"),
      search: t("filters.search"),
      searchPlaceholder: t("filters.searchPlaceholder"),
      categories: t("filters.categories"),
      allCategories: t("filters.allCategories"),
      subCategories: t("filters.subCategories"),
      allSubCategories: t("filters.allSubCategories"),
      tags: t("filters.tags"),
      allTags: t("filters.allTags"),
      showAll: t("filters.showAll"),
      showLess: t("filters.showLess"),
      city: t("filters.city"),
      allCities: t("filters.allCities"),
      location: t("filters.location"),
      favoritesOnly: t("filters.favoritesOnly"),
      openNow: t("filters.openNow"),
      reset: t("filters.reset"),
      locationPicker: {
        inputLabel: t("location.inputLabel"),
        placeholder: t("location.placeholder"),
        useCurrentLocation: t("location.useCurrentLocation"),
        locating: t("location.locating"),
        currentLocation: t("location.currentLocation"),
        savedLocations: t("location.savedLocations"),
        radius: t("location.radius"),
        anyDistance: t("location.anyDistance"),
        radiusHint: t("location.radiusHint"),
        clear: t("location.clear"),
        unavailable: t("location.unavailable"),
        permissionDenied: t("location.permissionDenied"),
        timeout: t("location.timeout"),
        noResults: t("location.noResults"),
      },
    },
  };
}
